/*    This file is part of nitlib.
 *
 *    Nitlib is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Lesser General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Foobar is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public License
 *    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#include "list.h"
#include "hashmap.h"

#define QUOTE(...) #__VA_ARGS__

static const char *free_contents = QUOTE(
	static void free_contents(void *key, void *storage)
	{
		fprintf(stderr, "Error: Tried to free generated map!\n");
		exit(1);
	});


static inline void
entry_gen(struct nit_hashentry *entry, FILE *output,
	  void (*key_print)(FILE *output, void *key, uint32_t key_size),
	  void (*storage_print)(FILE *output, void *storage))
{
	int entry_num = 0;

	for (; entry; entry = NIT_LIST_NEXT(entry)) {
		++entry_num;
		fputs("&(struct nit_hashentry) {", output);
		fprintf(output, "\n\t\t.key_size = %"PRIu32, entry->key_size);

		fputs(",\n\t\t.key = ", output);
		key_print(output, entry->key, entry->key_size);
		fputs(",\n\t\t.storage = ", output);
		storage_print(output, entry->storage);

		fputs(",\n\t\t.next.next = ", output);
	}
	fputs("NULL", output);
	for (; entry_num; --entry_num)
		fputc('}', output);
	fputc(',', output);
}

static inline void
bins_gen(struct nit_hashbin *bin, FILE *output, int bin_num,
	 void (*key_print)(FILE *output, void *key, uint32_t key_size),
	 void (*storage_print)(FILE *output, void *storage))
{
	int i = 0;

	fprintf(output, ",\n.bins = (struct nit_hashbin[%i]) {", bin_num);

	for (; i != bin_num; ++i, ++bin) {
		fprintf(output, "\n\t[%i].first = ", i);
		entry_gen(bin->first, output, key_print, storage_print);
	}

	fputs("\n}\n", output);
}

void
nit_hashmap_gen(struct nit_hashmap *map, FILE *output, const char *name,
		const char *headers, const char *compare,
		void (*key_print)(FILE *output, void *key, uint32_t key_size),
		void (*storage_print)(FILE *output, void *storage))
{

	fputs("/* Do not edit this file, it is generated! */\n", output);
	fputs("#include <stdio.h>\n"
	      "#include <stdlib.h>\n"
	      "#include <stdint.h>\n"
	      "\n", output);
	fputs(headers, output);
	fputc('\n', output);

	fputs(free_contents, output);
	fputc('\n', output);
	fputs(compare, output);
	fputc('\n', output);

	fprintf(output, "\nconst struct nit_hashmap %s = {", name);

	fputs("\n.free_contents = free_contents", output);
	fputs(",\n.compare = compare", output);
	fprintf(output, ",\n.bin_num = %u", map->bin_num);
	fprintf(output, ",\n.entry_num = %i", map->entry_num);
	fprintf(output, ",\n.primes_pointer = &(int) { %i }",
		*map->primes_pointer);
	bins_gen(map->bins, output, map->bin_num, key_print, storage_print);

	fputs("\n};", output);

}
